[phases.setup]
nixpkgs = ['python39', 'poetry', 'gcc']

[phases.install]
cmds = [
  'python -m pip install --upgrade pip',
  'pip install poetry',
  'poetry install --no-dev'
]

[phases.build]
cmds = [
  'python manage.py collectstatic --noinput'
]

[start]
cmd = 'daphne -b 0.0.0.0 -p $PORT config.asgi:application'

[variables]
DJANGO_SETTINGS_MODULE = "config.settings" 