[phases.setup]
nixpkgs = ['python39', 'python39Packages.pip', 'poetry', 'gcc']

[phases.install]
cmds = [
  'pip3 install --upgrade pip',
  'pip3 install poetry',
  'poetry install --no-dev'
]

[phases.build]
cmds = [
  'python manage.py collectstatic --noinput'
]

[start]
cmd = 'daphne -b 0.0.0.0 -p $PORT config.asgi:application'

[variables]
DJANGO_SETTINGS_MODULE = "config.settings"
WSGI_APPLICATION = "config.wsgi:application"
ASGI_APPLICATION = "config.asgi:application"
PYTHONUNBUFFERED = "1" 