[phases.setup]
nixpkgs = ['python39', 'gcc', 'curl']
cmds = [
  'curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py',
  'python get-pip.py --user',
  'rm get-pip.py'
]

[phases.install]
cmds = [
  'python -m pip install --user poetry',
  'poetry config virtualenvs.create false',
  'poetry install --no-dev'
]

[phases.build]
cmds = [
  'python manage.py collectstatic --noinput'
]

[start]
cmd = 'daphne -b 0.0.0.0 -p $PORT config.asgi:application'

[variables]
DJANGO_SETTINGS_MODULE = "config.settings"
WSGI_APPLICATION = "config.wsgi:application"
ASGI_APPLICATION = "config.asgi:application"
PYTHONUNBUFFERED = "1"
PATH = "/root/.local/bin:${PATH}" 