# Generated by Django 5.1.5 on 2025-02-08 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incidentstatetransition",
            options={},
        ),
        migrations.AlterField(
            model_name="incidentstatetransition",
            name="incident",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="state_transition",
                to="incidents.incident",
            ),
        ),
    ]
