# Generated by Django 4.2.19 on 2025-02-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0002_alter_incidentstatetransition_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incidentupdate",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="incidentupdate",
            name="incident",
        ),
        migrations.RemoveField(
            model_name="incidentupdate",
            name="org",
        ),
        migrations.RemoveField(
            model_name="incidentupdate",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="maintenanceupdate",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="maintenanceupdate",
            name="maintenance",
        ),
        migrations.RemoveField(
            model_name="maintenanceupdate",
            name="org",
        ),
        migrations.RemoveField(
            model_name="maintenanceupdate",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="impact",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="is_public",
        ),
        migrations.DeleteModel(
            name="IncidentStateTransition",
        ),
        migrations.DeleteModel(
            name="IncidentUpdate",
        ),
        migrations.DeleteModel(
            name="MaintenanceUpdate",
        ),
    ]
