# Generated by Django 5.1.5 on 2025-02-07 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="clerk_org_id",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["clerk_org_id"], name="organizatio_clerk_o_807b4f_idx"
            ),
        ),
    ]
