# Generated by Django 5.1.5 on 2025-02-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_service_deleted_at_service_deleted_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="service",
            name="display_order",
        ),
    ]
