# Generated by Django 4.2.19 on 2025-02-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_alter_service_options_remove_service_display_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incidentupdate",
            name="incident",
        ),
        migrations.AlterUniqueTogether(
            name="servicedependency",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="servicedependency",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="servicedependency",
            name="dependent_service",
        ),
        migrations.RemoveField(
            model_name="servicedependency",
            name="org",
        ),
        migrations.RemoveField(
            model_name="servicedependency",
            name="required_service",
        ),
        migrations.RemoveField(
            model_name="servicedependency",
            name="updated_by",
        ),
        migrations.AlterUniqueTogether(
            name="servicegroup",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="servicegroup",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="servicegroup",
            name="org",
        ),
        migrations.RemoveField(
            model_name="servicegroup",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="servicemetric",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="servicemetric",
            name="org",
        ),
        migrations.RemoveField(
            model_name="servicemetric",
            name="service",
        ),
        migrations.RemoveField(
            model_name="servicemetric",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="service",
            name="group",
        ),
        migrations.DeleteModel(
            name="Incident",
        ),
        migrations.DeleteModel(
            name="IncidentUpdate",
        ),
        migrations.DeleteModel(
            name="ServiceDependency",
        ),
        migrations.DeleteModel(
            name="ServiceGroup",
        ),
        migrations.DeleteModel(
            name="ServiceMetric",
        ),
    ]
